In [1]:
import sys
sys.path.append('../')

import cqt.datagen as dg
import pandas as pd
import pickle

from datetime import timedelta

In [2]:
key = '59103194-7503-441E-A849-1B961471734B'
source = 'coinapi'

In [3]:
request_btc = {'request_type' : 'ohlcv', \
               'symbol_id' : 'GEMINI_SPOT_BTC_USD', \
               'period_id' : '1DAY', \
               'time_start' : '2017-08-29T10:23:14', \
               'limit' : '100000'}

#lala=dg.get_req_str(source, request_btc)
#print(lala)
df_btc = dg.data_gen(source, request_btc, key, True)
df_btc.data.head()

https://rest.coinapi.io/v1/ohlcv/GEMINI_SPOT_BTC_USD/history?period_id=1DAY&time_start=2017-08-29T10:23:14&limit=100000

,price_close,price_open,price_high,price_low,time_close,time_open,trades_count,volume_traded,request_type,symbol_id,period_id,time_start,limit
0,4583.85,4590.00,4641.43,4495.05,2017-08-30T23:59:10.1240000Z,2017-08-30T00:00:00.8210000Z,14313,8832.814987,ohlcv,GEMINI_SPOT_BTC_USD,1DAY,2017-08-29T10:23:14,100000
1,4736.28,4583.00,4762.76,4579.91,2017-08-31T23:59:57.7490000Z,2017-08-31T00:00:12.3180000Z,11407,7268.196353,ohlcv,GEMINI_SPOT_BTC_USD,1DAY,2017-08-29T10:23:14,100000
2,4924.00,4736.28,4924.00,4709.28,2017-09-01T23:59:37.9730000Z,2017-09-01T00:00:11.4080000Z,11470,8188.879244,ohlcv,GEMINI_SPOT_BTC_USD,1DAY,2017-08-29T10:23:14,100000
3,4642.85,4924.00,4985.00,4505.00,2017-09-02T23:59:51.6230000Z,2017-09-02T00:00:17.9900000Z,20976,13402.051241,ohlcv,GEMINI_SPOT_BTC_USD,1DAY,2017-08-29T10:23:14,100000
4,4607.47,4643.63,4740.41,4460.05,2017-09-03T23:57:28.9910000Z,2017-09-03T00:00:00.0920000Z,12831,9479.341778,ohlcv,GEMINI_SPOT_BTC_USD,1DAY,2017-08-29T10:23:14,100000

In [13]:
request_btc_2 = {'request_type' : 'histoday', \
               'from_symbol' : 'BTC', \
                'to_symbol' : 'USD', \
               'time_start' : '2017-08-29T10:23:14', \
               'limit' : '253'}
source_2 = 'cryptocompare'
cfg_file = '../cqt/datagen/api.cfg' 
api_cfg = dg.read_api_cfg(cfg_file)

In [14]:
df_btc = dg.data_gen(source_2, request_btc_2, None, True)
df_btc.data.head()

https://min-api.cryptocompare.com/data/histoday?fsym=BTC&tsym=USD&limit=253&toTS=1504016594

,price_close,price_open,price_high,price_low,time_close,time_open,trades_count,volume_traded,request_type,from_symbol,to_symbol,time_start,limit
0,4735.11,4583.02,4765.07,4580.13,2017-08-30T20:00:00,2017-08-30T20:00:00,,3.389811e+08,histoday,BTC,USD,2017-08-29T10:23:14,253
1,4921.85,4735.11,4925.23,4690.17,2017-08-31T20:00:00,2017-08-31T20:00:00,,4.911404e+08,histoday,BTC,USD,2017-08-29T10:23:14,253
2,4573.80,4921.85,4976.52,4448.64,2017-09-01T20:00:00,2017-09-01T20:00:00,,7.477138e+08,histoday,BTC,USD,2017-08-29T10:23:14,253
3,4612.92,4573.80,4719.78,4397.74,2017-09-02T20:00:00,2017-09-02T20:00:00,,4.701358e+08,histoday,BTC,USD,2017-08-29T10:23:14,253
4,4267.45,4612.92,4621.01,4098.58,2017-09-03T20:00:00,2017-09-03T20:00:00,,7.372161e+08,histoday,BTC,USD,2017-08-29T10:23:14,253